import { createCliDb } from "./client";
const db = createCliDb();
const iits = ["Bhubaneswar|Bhubaneswar|Odisha","Bombay|Mumbai|Maharashtra","Mandi|Mandi|Himachal Pradesh","Delhi|New Delhi|Delhi","Indore|Indore|Madhya Pradesh","Kharagpur|Kharagpur|West Bengal","Hyderabad|Sangareddy|Telangana","Jodhpur|Jodhpur|Rajasthan","Kanpur|Kanpur|Uttar Pradesh","Madras|Chennai|Tamil Nadu","Gandhinagar|Gandhinagar|Gujarat","Patna|Patna|Bihar","Roorkee|Roorkee|Uttarakhand","ISM Dhanbad|Dhanbad|Jharkhand","Ropar|Rupnagar|Punjab","BHU Varanasi|Varanasi|Uttar Pradesh","Guwahati|Guwahati|Assam","Bhilai|Durg|Chhattisgarh","Goa|Ponda|Goa","Palakkad|Palakkad|Kerala","Tirupati|Tirupati|Andhra Pradesh","Jammu|Jammu|Jammu and Kashmir","Dharwad|Dharwad|Karnataka"];
const aiims = ["New Delhi|New Delhi|Delhi","Mangalagiri|Mangalagiri|Andhra Pradesh","Guwahati|Guwahati|Assam","Patna|Patna|Bihar","Darbhanga|Darbhanga|Bihar","Raipur|Raipur|Chhattisgarh","Rajkot|Rajkot|Gujarat","Bilaspur|Bilaspur|Himachal Pradesh","Jammu|Jammu|Jammu and Kashmir","Kashmir|Awantipora|Jammu and Kashmir","Deoghar|Deoghar|Jharkhand","Bhopal|Bhopal|Madhya Pradesh","Nagpur|Nagpur|Maharashtra","Bhubaneswar|Bhubaneswar|Odisha","Bathinda|Bathinda|Punjab","Jodhpur|Jodhpur|Rajasthan","Madurai|Madurai|Tamil Nadu","Bibinagar|Bibinagar|Telangana","Rae Bareli|Rae Bareli|Uttar Pradesh","Gorakhpur|Gorakhpur|Uttar Pradesh","Rishikesh|Rishikesh|Uttarakhand","Kalyani|Kalyani|West Bengal"];
const slug = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "");
async function main() {
  const rows = [...iits.map(x => { const [n,c,s] = x.split("|"); return { name: `Indian Institute of Technology ${n}`, city: c, state: s, group: "IIT", discipline: "Engineering", course: "B.Tech programmes", duration: 48, exam: "JEE Advanced through JoSAA" }; }), ...aiims.map(x => { const [n,c,s] = x.split("|"); return { name: `All India Institute of Medical Sciences ${n}`, city: c, state: s, group: "AIIMS", discipline: "Medical", course: "MBBS", duration: 66, exam: "NEET-UG through MCC counselling" }; })];
  await db.$transaction(async tx => { for (const row of rows) { const id = slug(row.name); const college = await tx.college.upsert({ where: { slug: id }, create: { slug: id, name: row.name, city: row.city, state: row.state, ownership: "PUBLIC", established: 2020, isDemo: true, overview: `${row.name} profile seeded for the CampusLens national catalogue. Programme, fee, placement and eligibility figures in this profile are illustrative placeholders pending institution-specific verification.` }, update: { name: row.name, city: row.city, state: row.state, ownership: "PUBLIC", isDemo: true } }); await tx.course.upsert({ where: { collegeId_slug: { collegeId: college.id, slug: slug(row.course) } }, create: { collegeId: college.id, slug: slug(row.course), name: row.course, discipline: row.discipline, degreeLevel: "UNDERGRADUATE", durationMonths: row.duration, annualFeeInr: 150000, eligibility: `Illustrative: admission through ${row.exam}; verify current requirements on the institution and counselling authority websites.` }, update: { name: row.course, annualFeeInr: 150000, eligibility: `Illustrative: admission through ${row.exam}; verify current requirements on the institution and counselling authority websites.` } }); await tx.placement.upsert({ where: { collegeId_year: { collegeId: college.id, year: 2025 } }, create: { collegeId: college.id, year: 2025, medianSalaryInr: 800000, averageSalaryInr: 950000, highestSalaryInr: 1800000, eligibleStudents: 100, placedStudents: 82 }, update: { medianSalaryInr: 800000, averageSalaryInr: 950000, highestSalaryInr: 1800000, eligibleStudents: 100, placedStudents: 82 } }); } }); console.log(`Seeded ${rows.length} IIT and AIIMS profiles with illustrative complete sections.`);
}
main().catch(() => { process.exitCode = 1; }).finally(() => db.$disconnect());
