"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
type Enrichment = { summary: string; courses: string[]; eligibility: string; fees: string; placements: string; fetchedAt: string; sourceUrl: string };
export function CollegeEnrichment({ slug, cached }: { slug: string; cached?: unknown }) {
  const [data, setData] = useState<Enrichment | null>(cached && typeof cached === "object" ? cached as Enrichment : null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const r = await fetch(`/api/colleges/${slug}/enrich`, { method: "POST" }); const b = await r.json(); if (!r.ok) throw Error(b.error); setData(b.data); } catch (e) { setError(e instanceof Error ? e.message : "Could not load details."); } finally { setLoading(false); } }
  return <section className="mb-12 rounded-panel border border-azure/15 bg-gradient-to-br from-white/80 to-azure/5 p-6 sm:p-8"><p className="eyebrow text-azure-ink">AI sourced profile</p>{!data ? <><p className="mt-3 max-w-xl text-body text-ink-secondary">Fetch a one-time summary from the official institution source. The result is cached for future visits.</p><Button className="mt-5" onClick={load} disabled={loading}>{loading ? "Reading official source…" : "Load verified details"}</Button></> : <><h2 className="mt-3 text-2xl font-medium">{data.summary}</h2><p className="mt-4 text-label text-ink-secondary">Courses: {data.courses.join(" · ")}</p><p className="mt-3 text-label text-ink-secondary">Eligibility: {data.eligibility}</p><p className="mt-3 text-label text-ink-secondary">Fees: {data.fees}</p><p className="mt-3 text-label text-ink-secondary">Placements: {data.placements}</p><p className="mt-5 text-xs text-ink-tertiary">Fetched {new Date(data.fetchedAt).toLocaleDateString("en-IN")} · Cached · <a className="underline" href={data.sourceUrl} target="_blank" rel="noreferrer">Source</a></p></>}{error && <p role="alert" className="mt-4 text-label text-danger-ink">{error}</p>}</section>;
}
